### ISSUE TITLE
Restructure TOP-meta repo

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/top-meta#281]
# Summary
Restructure this repo and try to keep most of the top-meta discord channel content in this repo to be updated with new bot commands similar to the new `/updatefaq` command for Odin-Bot
I can see some conflicts with some of the content of those channels already being stored in the [community guides of the curriculum](https://github.com/TheOdinProject/theodinproject/tree/main/app/views/guides/community) 

The reason I'm proposing this restructuring is because we worked on updating the FAQ roughly half a year ago and even though it was a good update, it kind of got forgotten about. Currently I personally have a hard time finding the discord specific content since they can be found both in the `theodinproject` repo community guides and in here. 

I wrote the below criteria based on the idea of keeping everything that's related to discord in this repo. Perhaps a better location to keep the channel information can be found if you think it should be in `theodinproject` repo community guides for example. The end goal would be to have them all in one logical place, and to have only one version of a file like the faq so we avoid having 3 different version floating around. 

With the current `/updatefaq` slash command it has become a lot less tedious to implement a change to the channel. In the past someone with access had to manually format and pass it through Dyno bot. That's now only one Odin-bot command away for the faq channel. Making quick edits to the documents can now be followed up with a bot command to refresh (or maybe even automatically in the future) and doesn't involve the more elaborate follow-up steps needed involving admins in the past.

It would be wonderful if proposing changes to and updating every meta discord channel becomes simpler (similar to faq). 

# Acceptance Criteria
All the points I can think of now:

## Rules
- [ ] Decide the best place for the "Rules" document since that currently resides in the `theodinproject` repo. We can also link to it here as we currently do with the Moderation Matrix mentioned below
- [ ] Rename or Replace the ["Moderation Matrix"](https://github.com/TheOdinProject/top-meta/blob/main/MODERATION/Moderation-Matrix.md) document depending on the main decision above. 
- [ ] Update both dead links to the rules in the ["Moderation Matrix" Document](https://github.com/TheOdinProject/top-meta/blob/main/MODERATION/Moderation-Matrix.md) if decided the rules will remain in the main repo.
- [ ] Create a slash command to update the rules discord channel 
 
## FAQ 
- [x] The most current faq Document will reside in this repo 
- [x] slash command to update faq

## Roles 
- [ ] The most current roles Document will reside in this repo 
- [ ] Decide on one description of the discord roles, resulting in one document/text for the Discord channel instead of the current discord content and [this document](https://github.com/TheOdinProject/top-meta/blob/main/about/discord-roles.md)
- [ ] Create a slash command to update the roles discord channel but keep in mind the self-assigned roles in that channel as well

*perhaps the self assigning of roles can also be done with the discord community features nowadays, I haven't fully checked the options*

## Contact Moderators 
- [ ] Add a channel explanation document for the top message on when/how the contact-moderators channel should be used (copy current channel message on this)
- [ ] The most current Modmail guide and channel explanation will reside in this repo 
- [ ] Create a slash command to update the contact-moderators discord channel with both of the above files

## Bot updates 
- [ ] Decide if the slash commands should be updated to an automatic update when a doc gets a new commit. [discord idea from Xari](https://discord.com/channels/505093832157691914/991035463949254767/1110907326468194314)

## Repo Structure
- [ ] Place the discord channel specific docs in their own folder 
- [ ] Decide on a staff folder for the meeting notes, onboarding, guidelines and everything staff related
- [ ] Add the application for Professional to the Roles

**Comment by JustWaveThings** [comment]
Sorry, finger slipped on a checkbox... Don't want anyone searching for ninja edits...

**Comment by ChargrilledChook** [comment]
I'm a fan of the concept broadly, top meta seems like a fine place to put it, but maybe there are other options. Perhaps a `community` repo if it's distinct enough from meta, but if it's organized in one spot moving it is easy.

Regarding having things be in the main app repo, I would strongly prefer it _not_ to be the source of truth for these kind of community based things. I would also support moving those things out of the app repo where it makes sense / isn't directly relevant to the app

Will attempt to give more detailed feedback on specifics when I get a chance

**Comment by KevinMulhern** [comment]
Thanks for putting this together @ManonLef, sounds like a great idea to me.

**Comment by rlmoser99** [comment]
In general everything sounds like a good idea. I like the idea of a `community` repo. The only concern that I have is
the rules in `theodinproject` repo is not a markdown file, so I am not sure we can do the same update command that we have with the faq.

**Comment by ManonLef** [comment]
@rlmoser99 that’s the only file receiving special treatment in this plan because of that. Even though it’s a community document, it’s the only one having a dedicated webpage as well. 

I thought moving that to another repo while also keeping it on the website might not be straightforward. Glad you’re all positive about the idea and willing to think about the above issue.

**Comment by wise-king-sullyman** [comment]
Sounds like a great idea to me as well 🔥 I feel like this repo makes sense for it, but also wouldn't be opposed to a `community` specific repo for these kinds of things.

**Comment by ManonLef** [comment]
I really like the idea of a `community` repo as well

**Comment by ManonLef** [comment]
I will take this on once I have a little more time. Probably when I'm out of the final CS project :)
