### ISSUE TITLE
Move all community guides to top-meta

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/top-meta#294]
Per [this issue](https://github.com/TheOdinProject/theodinproject/issues/4022) on the main app, we're working on extracting the rules from the main app to live in this repository. For the sake of consistency (and because it'll just be better), we've also decided to go ahead and move the other community guides here as well.

You can see a list of each of the community guides on the main app [here](https://www.theodinproject.com/guides/community)

Currently, the rules are the only community guide that has a markdown file on top-meta. We need to add the other 3 guides and probably make a folder for them to be grouped under. You can find the guides in the main app under `app/views/guides/community`. You'll have to them from their `erb` template format over to markdown.
### Tasks
- [ ] Make directory for the guides to live in. Probably just called `community-guides/`
- [ ] Add [Expectations](https://www.theodinproject.com/guides/community/expectations)
- [ ] Add [How to Ask Technical Questions](https://www.theodinproject.com/guides/community/how_to_ask)
- [ ] Add [Help Yourself Before Asking Others](https://www.theodinproject.com/guides/community/before_asking)

**Comment by rlmoser99** [comment]
Is there a reason we are putting them on top-meta? Would it be possible to have them be on the curriculum repo? 

Currently we do not consider top-meta a repo that is open for others to contribute to, though we have it public in an effort to be transparent.
https://github.com/TheOdinProject/top-meta#faq

**Comment by JoshDevHub** [comment]
@rlmoser99 Ah I see. Thanks for linking these PRs!

We could *probably* put them in the curriculum, although the implementation might be kind of strange because the guides aren't lessons (don't belong to course or path, can never be a project, etc.). Another idea could be to create a "community" repo, an idea that gets mentioned [in this top-meta restructure issue](https://github.com/TheOdinProject/top-meta/issues/281).

I'm definitely not attached to putting them here, although I do think that even top-meta would be an improvement. Staff wouldn't need to understand how to navigate a Rails project to change the rules (or any of the other guides). I agree that having them fully open to contributions is probably a good idea though, so top-meta wouldn't be the ideal spot.
