### ISSUE TITLE
[TEMPLATE] - User story / work item

### ISSUE THREAD

**Issue by kashura** [TheOdinProject/top-meta#4]
The purpose of using this template is to break down large initiatives into smaller, independent pieces. The idea is that as we break down the big initiatives, people are able to contribute efficiently to meet acceptance criteria set in the ticket. 

The work item should utilize these suggested components, but use your best judgement:

# Summary
What is the purpose of this deliverable? How will it bring us closer to finishing the initiative?

**Example**: We need to create a logo for the TOP styled leggings. We can use the proceeds to raise the funds for hosting costs. 

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
**Example**:
- [ ] The design should be on both legs.
- [ ] The design should be above knee, but below the hip.
- [ ] The colors should include the most annoying shades of green and orange.
